using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using AIT.DMF.Contracts.Exceptions;

namespace AIT.DMF.DependencyService.Test
{
    /// <summary>
    ///This is a test class for DependencyGraphCreatorTest and is intended
    ///to contain all DependencyGraphCreatorTest Unit Tests
    ///</summary>
    [TestClass()]
    public class DependencyGraphCreatorTest
    {
        #region # Autogenerated by MSTest
        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            Platform.Initialize();
        }
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion
        #endregion

        #region # DependencyGraphCreatorConstructor Test
        /// <summary>
        /// Test for DependencyGraphCreator constructor with valid dependency definition filename.
        ///</summary>
        [TestMethod()]
        public void DependencyGraphCreatorConstructorTest_ValidDependencyDefinitionFilename()
        {
            string dependencyDefinitionFileName = "component.targets";
            DependencyGraphCreator target = new DependencyGraphCreator(dependencyDefinitionFileName);
        }

        /// <summary>
        /// Test for DependencyGraphCreator constructor with empty string as dependency definition filename.
        ///</summary>
        [TestMethod()]
        [ExpectedException(typeof(DependencyServiceException))]
        public void DependencyGraphCreatorConstructorTest_InvalidDependencyDefinitionFilename()
        {
            string dependencyDefinitionFileName = String.Empty;
            DependencyGraphCreator target = new DependencyGraphCreator(dependencyDefinitionFileName);
        }
        #endregion

    }
}
